[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
[window]
padding = { x = 5, y = 5 }
decorations = "full"
opacity = 0.8
blur = true
[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }
size = 19
[mouse]
hide_when_typing = true
